name: Bygg og publiser docker-image for master

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**

jobs:
  build-and-publish-on-master:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut koden
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.13

      - name: Finn cache-variabler
        uses: navikt/pb-common-gh-actions/cache-prep@v2

      - name: Sett opp cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.CACHE_PATHS }}
          key: ${{ runner.os }}${{ env.CACHE_KEY_NAMESPACE }}${{ hashFiles(env.CACHE_KEY_HASHED_PATH) }}

      - name: Bygg prosjekt og kjør tester
        run: gradlew clean build

      - name: Bygg, tag og push Docker image
        uses: navikt/pb-common-gh-actions/docker-publish@v2
        with:
          TAG_LATEST: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
